server:
  port: 7000

spring:
  application:
    name: review-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_db_user
    password: your_db_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use 'validate', 'create', 'create-drop', or 'none' for other behaviors
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true